name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  
      - name: Display Build Number
        run: echo "This is build number ${{ github.run_number }}"

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release /p:Version=8.1.${{ github.run_number }}

      - name: Test
        run: dotnet test --no-build --configuration Release --verbosity normal
