name: Core Lib Build, Test and Deploy to NuGet

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # Replace with your project's required version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release
      
    - name: List files in test directory
      run: ls YourTestProject/bin/Release/net8.0/
      
    - name: Test
      run: dotnet test McGurkin.sln --no-build --verbosity normal
